---

name: "Update README.md"


on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:


jobs:
  update:
    name: "Update this repo's README with recent activity"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2

      - name: "Update README.md"
        uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
